### PR TITLE
try quotes

### PR DESCRIPTION
**Pull request by marcoscaceres**
Seems the $AUTHORIZATION is not being dereferenced... maybe quotes helps?

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Looking at other travis config files, they have things that use $ENCRYPTED_VARS quoted... so thought it was worth a shot.

**Comment by marcoscaceres** [comment]
Hmm... I wonder if anyone a bit more, um, "Unixy" can have a look at what I might be doing wrong? @dontcallmedom maybe? We encrypted vars working with auto publish, so I'm a bit lost and unsure what I might be doing wrong 😰

**Comment by tripu** [comment]
@marcoscaceres, have you tried adding your GH API key as [an environment variable on Travis config itself](https://travis-ci.org/w3c/spec-generator/settings#ember973), instead?

**Comment by marcoscaceres** [comment]
I haven't, no. I don't have rights to the repo or travis, so can't access them. If you ping me on IRC, I can share the key with you (securely).

**Comment by marcoscaceres** [comment]
Closed via #87

**Pull request closed without merging**
