### PR TITLE
fix(package): update respec to version 19.4.0

### PR DESCRIPTION
**Pull request by tripu**
Closes #65

### CODE REVIEW

**Comment by saschanaz** [comment]
:+1: but it seems there is no Travis configuration file?

**Comment by tripu** [comment]
Ah, we never had a `.travis.yml` in this repo in the first place, did we?

(The other day I re-enabled builds for a bunch of W3C repos after a recent Travis CI incidence; I must have enabled this one too, by mistake. I just reverted that.)

@marcoscaceres, does this change look okay to you, too?

**Comment by tripu** [comment]
(Or @deniak)

**Comment by tripu** [comment]
Tested and :+1: (I pushed an empty commit just to make sure Travis is now disabled again here).

**Pull request merged**
