### PR TITLE
fix(package): update respec to version 18.0.0

### PR DESCRIPTION
**Pull request by tripu**
Closes #44

### CODE REVIEW

**Comment by tripu** [comment]
@marcoscaceres, I can't make this new version work with spec-generator, either&hellip;

I don't see errors on the Node.js console now, but when [trying to process an ED like `https://w3c.github.io/webrtc-pc/`](http://localhost:3000/?type=respec&shortname=webrtc&url=https://w3c.github.io/webrtc-pc/), the result is this error:

    \u001b[33m💣 Not a ReSpec source document?\u001b[39m \u001b[36mhttps://w3c.github.io/webrtc-pc/?publishDate=2017-10-23\u001b[39m

(Apologies if for some reason this is WIP and not supposed to work yet, or if this is not a good spec for tests.)

Any idea?

**Comment by marcoscaceres** [comment]
Odd. I’ll take a look.

**Comment by marcoscaceres** [comment]
Ok, couple of things wrong... some on my part, some we need to fix in the RTC spec. 

1. the error message is actually correct. That's not a ReSpec doc :) The one we actually want to be checking is "webrtc.html". That's just a detail, but thought I would mention it.  
1. The generator (respec2html.js) was expecting "respec-w3c-common.js" to be hosted on the W3C server. The spec is hosting it's own ReSpec... so that's a bug on my part. I'm sending a fix. 

This one requires the RTC spec to upgrade to 18: 

1. The generator relies on a new `exportDocument()` method provided by ReSpec 18. If it's not there, generation will fail.  

Unfortunately, it's a bit of a mess for me to make that backwards compatible. I'll add some error messages, but that's as much as I can do right now.

**Comment by marcoscaceres** [comment]
Prepared PR... waiting on Travis 😬 ... being really slow today :(

**Comment by marcoscaceres** [comment]
Still not 100% fixed, sorry... will keep working on it tomorrow 😥

**Comment by marcoscaceres** [comment]
Might be good now, on 18.0.2.

**Pull request closed without merging**
