### PR TITLE
Revert "fix(package): update respec to version 19.2.2"

### PR DESCRIPTION
**Pull request by deniak**
Reverts w3c/spec-generator#63

### CODE REVIEW

**Comment by deniak** [comment]
@marcoscaceres the latest version of respec is breaking spec-generator with the following error
```
{"error":"Failed to launch chrome!\n[0213/130234.446141:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.\n#0 0x559e6f2502ec base::debug::StackTrace::StackTrace()\n#1 0x559e6f26773c logging::LogMessage::~LogMessage()\n#2 0x559e6e2ec0d1 content::ZygoteHostImpl::Init()\n#3 0x559e6df66045 content::BrowserMainLoop::EarlyInitialization()\n#4 0x559e6df6c222 content::BrowserMainRunnerImpl::Initialize()\n#5 0x559e73138059 headless::HeadlessContentMainDelegate::RunProcess()\n#6 0x559e6ef8cf60 content::RunNamedProcessTypeMain()\n#7 0x559e6ef8d975 content::ContentMainRunnerImpl::Run()\n#8 0x559e6ef96c5f service_manager::Main()\n#9 0x559e6ef8c481 content::ContentMain()\n#10 0x559e731371fa headless::(anonymous namespace)::RunContentMain()\n#11 0x559e7313726e headless::HeadlessBrowserMain()\n#12 0x559e6ef93a6a headless::HeadlessShellMain()\n#13 0x559e6d8191c5 ChromeMain\n#14 0x7fccfcb772b1 __libc_start_main\n#15 0x559e6d81902a _start\n\nReceived signal 6\n#0 0x559e6f2502ec base::debug::StackTrace::StackTrace()\n#1 0x559e6f24fe51 base::debug::(anonymous namespace)::StackDumpSignalHandler()\n#2 0x7fcd02ad40c0 <unknown>\n#3 0x7fccfcb89fcf gsignal\n#4 0x7fccfcb8b3fa abort\n#5 0x559e6f24eaa5 base::debug::BreakDebugger()\n#6 0x559e6f267b3f logging::LogMessage::~LogMessage()\n#7 0x559e6e2ec0d1 content::ZygoteHostImpl::Init()\n#8 0x559e6df66045 content::BrowserMainLoop::EarlyInitialization()\n#9 0x559e6df6c222 content::BrowserMainRunnerImpl::Initialize()\n#10 0x559e73138059 headless::HeadlessContentMainDelegate::RunProcess()\n#11 0x559e6ef8cf60 content::RunNamedProcessTypeMain()\n#12 0x559e6ef8d975 content::ContentMainRunnerImpl::Run()\n#13 0x559e6ef96c5f service_manager::Main()\n#14 0x559e6ef8c481 content::ContentMain()\n#15 0x559e731371fa headless::(anonymous namespace)::RunContentMain()\n#16 0x559e7313726e headless::HeadlessBrowserMain()\n#17 0x559e6ef93a6a headless::HeadlessShellMain()\n#18 0x559e6d8191c5 ChromeMain\n#19 0x7fccfcb772b1 __libc_start_main\n#20 0x559e6d81902a _start\n  r8: 0000000000000000  r9: 00007fff44aa7820 r10: 0000000000000008 r11: 0000000000000246\n r12: 00007fff44aa7f28 r13: 00007fff44aa7f18 r14: 00007fff44aa7f20 r15: 00007fff44aa7ad0\n  di: 0000000000000002  si: 00007fff44aa7820  bp: 00007fff44aa7a60  bx: 0000000000000006\n  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fccfcb89fcf  sp: 00007fff44aa7898\n  ip: 00007fccfcb89fcf efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000\n trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000\n[end of stack trace]\nCalling _exit(1). Core file will not be generated.\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"}
```

Does it have new requirements?

**Comment by marcoscaceres** [comment]
Ah, you might be hitting this:
https://github.com/w3c/respec/blob/develop/.travis.yml#L11

We might need to also update your TravisCI config with “sudo: reqired”... or is this happening locally? 

Cc @saschanaz

**Comment by saschanaz** [comment]
Ah, it seems this is more related with https://github.com/w3c/respec/pull/1483. Sandboxing is disabled in Electron whereas Chromium enables it by default.

**Comment by saschanaz** [comment]
(Should we provide an option to disable it?)

**Comment by marcoscaceres** [comment]
Whatever is easiest. Critical thing is that ReSpec work with the spec generator, as it’s our most important consumer.

**Comment by deniak** [comment]
> We might need to also update your TravisCI config with “sudo: reqired”... or is this happening locally?

It wasn't on travis. I tried it with spec-generator and that's the error I was getting

**Comment by marcoscaceres** [comment]
Incoming fix. https://github.com/w3c/respec/pull/1504

**Comment by tripu** [comment]
@marcoscaceres, is it safe to upgrade now to Respec `19.4.0`, then?
#66.

**Comment by saschanaz** [comment]
It does not disable sandbox by default, it just gives an option for it. So the required thing here is to use the option.

**Comment by saschanaz** [comment]
https://github.com/w3c/spec-generator/blob/06df1b71fc275cffc40a02db1a46eecf3f325f69/generators/respec.js#L16

```js
respecWriter(url, '/dev/null', {}, { timeout: 20000, disableSandbox: true })
```

**Comment by tripu** [comment]
@saschanaz, @marcoscaceres: #66?

**Pull request closed without merging**
