### PR TITLE
Remove the dependency to tr.rdf. Rely on the shortlink instead

### PR DESCRIPTION
**Pull request by deniak**
Downloading `tr.rdf` to get the previous version is a bit overkill and makes services like validator to time out (see #11). That MR removes that dependency by looking directly at the shortlink. This will be replaced again when we'll have the API.

### CODE REVIEW

**Comment by tripu** [comment]
I don't think this makes spec-generator fast enough in all cases to please the most impatient pieces in our tool chain, namely the HTML checker. But it's an improvement in terms of performance, while we get to a better solution.

**Comment by tripu** [comment]
@darobin, [`github.com/tmpvar/jsdom`](https://github.com/tmpvar/jsdom)?

**Comment by sideshowbarker** [comment]
> @darobin, github.com/tmpvar/jsdom?

Yup. I think switching to `jsdom` would be great. We know some of the people working on that, so if we ran into issues I know we could get them worked out.

Opened #13 to track this as an enhancement to consider.

**Comment by darobin** [comment]
Yes, that one. We've run into (severe) performance issues in the past, but they were extremely responsive and fixed them. I reckon it would be worth giving it a shot.

**Pull request merged**
