### PR TITLE
use the latest minor update of respec

### PR DESCRIPTION
**Pull request by deniak**

### CODE REVIEW

**Comment by tripu** [comment]
@marcoscaceres, @halindrome, @deniak:

Shall we `npm update` and restart [our instance of `spec-generator` on labs](https://labs.w3.org/spec-generator/) (the one Echidna uses) now, or are you still busy with changes right now?

I see [the last version published of `respec` is `3.2.105`, four days ago](https://www.npmjs.com/package/respec).

**Comment by halindrome** [comment]
We aren't ready.  The last useful version is 3.2.97.  If you want to push
with that, go ahead.  If you do, set useExperimentalStyles to true all the
time and it will (probably) pass pubrules.

You can find a copy of that version at
https://spec-ops.io/respec-w3c-common.js

On Mon, Mar 7, 2016 at 7:53 AM, tripu <notifications@github.com> wrote:

> @marcoscaceres <https://github.com/marcoscaceres>, @halindrome
> <https://github.com/halindrome>, @deniak <https://github.com/deniak>:
>
> Shall we npm update and restart our instance of spec-generator on labs
> <https://labs.w3.org/spec-generator/> (the one Echidna uses) now, or are
> you still busy with changes right now?
>
> I see the last version published of respec is 3.2.105, four days ago
> <https://www.npmjs.com/package/respec>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/spec-generator/pull/25#issuecomment-193255636>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Hold a few more days. Fixes and new release coming in the next 24hours.

**Comment by marcoscaceres** [comment]
Also, what are you using as the backend for the spec generator? Is that code somewhere? We want to add more support for promises to ReSpec, but Phantomjs is preventing us from doing that successfully so we need to find a solution (eg, getting the spec generator to inject the Promise polyfill early).

**Comment by tripu** [comment]
Holding off, then.

@marcoscaceres, do you mean [`w3c/spec-generator`](https://github.com/w3c/spec-generator)? The commit that is deployed in production is [`6028743864f8458dac745490b4284071b40b6286`](https://github.com/w3c/spec-generator/tree/6028743864f8458dac745490b4284071b40b6286). It's running on Node.js LTS `4.x` and `phantomjs` `^1.9.19`.

**Comment by marcoscaceres** [comment]
@tripu, thanks for the info. Will make sure I test against it.

**Comment by marcoscaceres** [comment]
We made a stable release. Please update your version of ReSpec if you haven't already.

**Comment by halindrome** [comment]
They have been updating it.

**Comment by marcoscaceres** [comment]
Excellent! Just wanted to make sure.

**Pull request merged**
